.linux: &linux
  image: docker.gitlab.gwdg.de/jlebert/quickmultrecviewer

.gcc: &gcc
  <<: [*linux]
  image: docker.gitlab.gwdg.de/jlebert/quickmultrecviewer/gcc
  cache:
    key: docker-gcc
    paths:
      - .ccache

.clang: &clang
  <<: [*linux]
  image: docker.gitlab.gwdg.de/jlebert/quickmultrecviewer/clang
  cache:
    key: docker-clang
    paths:
      - .ccache

.osx: &osx
  tags:
    - osx

.windows: &windows
  tags:
    - windows

.xcode_generator: &xcode_generator
  CMAKE_GENERATOR: 'Xcode'
  CMAKE_OSX_DEPLOYMENT_TARGET: '10.13.6'

.vs_generator: &vs_generator
  CMAKE_GENERATOR: 'Visual Studio 16 2019'
  CMAKE_GENERATOR_PLATFORM: 'x64'

.build_make: &build_make
  script:
    - JOB_NAME=( $CI_JOB_NAME )
    - export BUILD_TYPE=${JOB_NAME[@]:(-1)}
    - echo "BUILD_TYPE=${BUILD_TYPE}"
    - echo "CMAKE_PARAMS=${CMAKE_PARAMS}"
    - cmake -H. -Bbuild -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ${CMAKE_PARAMS[@]} -Wdev
    - cd build
    - cmake --build . --parallel 4
    - |
      if [ "$BUILD_APPIMAGE" = true ]
      then
        curl -L -o linuxdeploy-x86_64.AppImage https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        chmod +x linuxdeploy-x86_64.AppImage
        OUTPUT="quickVidViewer.AppImage" ./linuxdeploy-x86_64.AppImage --appimage-extract-and-run -e quickVidViewer -d ../vendor/quickVidViewer.desktop -i ../vendor/MultiRecorderVideo.png --appdir AppDir --output appimage
      fi

  dependencies: []

.build_config_generator: &build_config_generator
  script:
    - JOB_NAME=( $CI_JOB_NAME )
    - export BUILD_TYPE=${JOB_NAME[@]:(-1)}
    - echo "BUILD_TYPE=${BUILD_TYPE}"
    - echo "CMAKE_PARAMS=${CMAKE_PARAMS}"
    - cmake -H. -Bbuild -G "${CMAKE_GENERATOR}" -DCMAKE_GENERATOR_PLATFORM="${CMAKE_GENERATOR_PLATFORM}" ${CMAKE_PARAMS[@]} -Wdev
    - cd build
    - cmake --build . --config ${BUILD_TYPE} --parallel 4
  dependencies: []



.docker_build: &docker_build
  <<: [*build_make]
  before_script:
    - export CCACHE_DIR=`pwd`/.ccache
    - export CCACHE_SLOPPINESS="file_macro,pch_defines,time_macros"
    - ccache -s

gcc Release:
  <<: [*gcc, *docker_build]
  variables:
    CMAKE_PARAMS: -DSTATIC_GCC=ON
    BUILD_APPIMAGE: "true"
  artifacts:
    paths:
      - build/quickVidViewer.AppImage
    expire_in: 3 months

gcc Debug:
  <<: [*gcc, *docker_build]

clang Release:
  <<: [*clang, *docker_build]
  variables:
    CXXFLAGS: "-DCLI11_HAS_FILESYSTEM=0 -stdlib=libc++ -Wno-error=unused-command-line-argument"

#osx Release:
#  <<: [*osx, *build_config_generator]
#  variables:
#    CMAKE_GENERATOR: 'Xcode'
#    CMAKE_OSX_DEPLOYMENT_TARGET: '10.13.6'
#    CMAKE_PARAMS: '-DCMAKE_OSX_DEPLOYMENT_TARGET=10.13.6 -DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/'
#  artifacts:
#    paths:
#      - build/Release/quickVidViewer
#    expire_in: 3 months
#  before_script:
#    - date
#    - curl --insecure -o MacOSX10.13.sdk.tar.xz -L https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX10.13.sdk.tar.xz
#    - tar xf MacOSX10.13.sdk.tar.xz
#    - sudo mv MacOSX10.13.sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
#    - date
#  after_script:
#    - otool -l build/Release/quickVidViewer | grep -A 3 LC_VERSION_MIN_MACOSX

windows Release:
  <<: [*windows, *build_config_generator]
  variables:
    <<: *vs_generator
  artifacts:
    paths:
      - build/Release/quickVidViewer.exe
    expire_in: 3 months

glsl:
  <<: [*linux]
  only:
    changes:
      - src/shaders/*
  script:
    - glslangValidator -C src/shaders/*