[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools_scm>=6.2",
    "scikit-build",
    "cmake>=3.18",
    "ninja"
]
build-backend="setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/python/monochrome/_version.py"
fallback_version = "0.1"